/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conexao.Conexao_BD;
import Dao.LucroDao;
import Model.LucroModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ander
 */
public class LucroView extends javax.swing.JFrame {

    /**
     * Creates new form contador
     */
    public LucroView() {
        initComponents();
         visualizarLucro();
         operacoesParaDiaAtual();
         //Centralizando a view ao centro da monitor;
        setLocationRelativeTo(null);
    }

    
    
    String codigoLucro="";
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        totalLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabLucro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        deleta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelInvesti = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelLucro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabLucro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codLucro", "codProd", "qtd Total", "ValorUnit", "valorTotal", "ValorComprar", "ValorInvestido", "ValorGanhor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabLucro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabLucroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabLucro);

        jLabel1.setText("Código:");

        deleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/claro.png"))); // NOI18N
        deleta.setText("Deletar");
        deleta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("Detalhe do Lucro");

        labelInvesti.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        labelTotal.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Valor Investimento:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Valor De Todas Vendas:");

        labelLucro.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Valor Do Lucro:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelInvesti, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                        .addGap(56, 56, 56))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(totalLb)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelLucro, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(deleta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInvesti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 142, Short.MAX_VALUE)
                    .addComponent(totalLb)
                    .addGap(0, 437, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        //ESSAS VARIAVEIS ESTÃO ALTERADAS PARA REALIZAR AS OPERAÇÕES DO DIA ATUAL
       
       
       
         //variável para receber o total da soma de todas as despesas do dia
      double ValorTotalDespesasDiaAtual=0; 
     //variavél para receber o valor do capital do dia presente
      double capitalDiaAtual  =0;
        //As Variaveis para receber os valores da jframe Investimento são else:
        //investimento,lucro, todo valor dos produtos vendidos;
       double valorDeTodoInvestimentoDiaAtual=0;
       double valorTotalDeTDProdutosVendidoDiaAtual=0;
       double valorDeTodoGanhoInvestidoDiaAtual=0;
       double valorDeTodoLucroDiaAtual=0;
       
    
      DecimalFormat def = new DecimalFormat("#,##0.00");
    private void tabLucroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabLucroMouseClicked
          
            //Seta os dados de cada linha a ser clicadar da tabela;
            txtCodigo.setText(tabLucro.getValueAt(tabLucro.getSelectedRow(),0).toString());
 
    }//GEN-LAST:event_tabLucroMouseClicked

    private void deletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletaActionPerformed
     
        int op =JOptionPane.showConfirmDialog(null, "Deseje deleta tudo ?");
        if(op==JOptionPane.YES_OPTION){
         
         //Instânciando a classe ComprovanteDao;
        LucroDao dao = new LucroDao();
        dao.deletaTODOSLucros();
        }else{
            
         //Instânciando a classe ComprovanteDao;
        LucroDao dao = new LucroDao();
        dao.deletaLucros(txtCodigo.getText());
        visualizarLucro();
        }
    }//GEN-LAST:event_deletaActionPerformed
 
     public void addDadosLucros(){
      
         
         
         
         
     }
     //Método para visualizar dados do lucro;
    public void visualizarLucro() {
        DefaultTableModel modelo = (DefaultTableModel) tabLucro.getModel();
        //Método para não repetir os dados na tabela lucro
        modelo.setNumRows(0);
        //Instânciando a classe ComprovanteDao;
        LucroDao dao = new LucroDao();
        //Um Laço de repetição para lista todas compras na tabela de lucro no banco de dados; 
        for (LucroModel lc: dao.visualizarLucro()) {
            modelo.addRow(new Object[]{
                //Passando os objetos 
             lc.getCodigoLucro(),
             lc.getCodigoProduto(),
             lc.getQuantidade(),
             lc.getValorUnitario(),
             lc.getValorTotal(),
             lc.getValorDcomprar(),
             lc.getValorInvestir(),
             lc.getValorGanhor(),
             lc.getData()

            });
        }

    }

 //Método para visualizar dados do lucro;
    public void visualizarLucroComCodigo() {
        DefaultTableModel modelo = (DefaultTableModel) tabLucro.getModel();
        //Método para não repetir os dados na tabela lucro
        modelo.setNumRows(0);
        //Instânciando a classe ComprovanteDao;
        LucroDao dao = new LucroDao();
        //Um Laço de repetição para lista todas compras na tabela de lucro no banco de dados; 
        for (LucroModel lc: dao.visualizarLucroPeloCodigo(txtCodigo.getText())) {
            modelo.addRow(new Object[]{
                //Passando os objetos 
             lc.getCodigoLucro(),
             lc.getCodigoProduto(),
             lc.getQuantidade(),
             lc.getValorUnitario(),
             lc.getValorTotal(),
             lc.getValorDcomprar(),
             lc.getValorGanhor(),
             lc.getData()

            });
        }

    }
    
    
    
  
    
         //Método para seta o código do lucro;
    public void setacodigodoLucro() {

        try {
            Connection Conn = Conexao_BD.getConnection();

            //comando para seta o código do lucro
            String sql = "SELECT codLuc from lucro ";
            PreparedStatement Patm = Conn.prepareStatement(sql);
            //executar
            ResultSet Rst = Patm.executeQuery();

            if (Rst.next()) {
            //Setando o codLud 
               codigoLucro=Rst.getString("codLuc");
                
              JOptionPane.showMessageDialog(null," Código do lucro é "+codigoLucro);

            } else {
                  JOptionPane.showMessageDialog(null,"codigo não existe !");
              
            }

            //Fechando conexão ResultSet;
            Rst.close();

            //Fechando conexão PreparedStatement;
            Patm.close();

            //Fechando conexão Connection;
            Conn.close();

        } catch (SQLException e) {
            //caso de error exiber essa mensagem
            JOptionPane.showMessageDialog(null, "Código não Encontrado !");
        }

    }
  
     
      
 
       
       //Método para realizar as somas do investimentos, lucro e de todos produtos vendidos  
       public  void RealizarOsCalculosEsetaValoresDiaAtual(){
         
           try {
            Connection Conn = Conexao_BD.getConnection();
        
            //comando para realizar a soma
            String sql = "SELECT (round(sum(valorinvest))),(round(sum(total))),(round(sum(Ganhor))) FROM lucro;";

            PreparedStatement Patm = Conn.prepareStatement(sql);
            
            ResultSet Rst = Patm.executeQuery();
        
            while (Rst.next()) {
                                
                 valorDeTodoInvestimentoDiaAtual=Rst.getDouble("(round(sum(valorinvest)))");
                
                  valorTotalDeTDProdutosVendidoDiaAtual= Rst.getDouble("(round(sum(total)))");
                  valorDeTodoGanhoInvestidoDiaAtual= Rst.getDouble("(round(sum(Ganhor)))");
             
                   labelInvesti.setText(""+valorDeTodoInvestimentoDiaAtual);
                   labelTotal.setText(""+valorTotalDeTDProdutosVendidoDiaAtual);
                   labelLucro.setText(""+valorDeTodoGanhoInvestidoDiaAtual);
                  
                  
              // Passando os valores para 2 casas  decimais
              String valorInvestir=def.format(valorDeTodoInvestimentoDiaAtual);
              //String valorTotal=def.format(valorTotalDeTDProdutosVendido);
              String valorTOTAL=def.format(valorTotalDeTDProdutosVendidoDiaAtual);
              String valorDeTodoGanhoInvestidor=def.format(valorDeTodoGanhoInvestidoDiaAtual);
                  
                  labelInvesti.setText("R$ "+valorInvestir);
                   labelTotal.setText("R$ "+valorTOTAL);
                   labelLucro.setText("R$ "+valorDeTodoGanhoInvestidor);
                  
            }

            Rst.close();
            Patm.close();
            Conn.close();

        } catch (SQLException e) {
        
         
            
            JOptionPane.showMessageDialog(null, "Soma do dia de hoje não realizada !");
        }
        
     }
     
     
     //método para realizar as operações para dia atual
        public void operacoesParaDiaAtual(){
             
        RealizarOsCalculosEsetaValoresDiaAtual();
        
        }

     
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LucroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LucroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LucroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LucroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LucroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInvesti;
    private javax.swing.JLabel labelLucro;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tabLucro;
    private javax.swing.JLabel totalLb;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
