/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conexao.Conexao_BD;
import Dao.RelatorioDao;
import Model.RelatorioModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ander
 */
public class Relatorio_vd extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio_vd
     */
    public Relatorio_vd() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TOTALvendas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodRe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodVend = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        bTapagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        visualizar = new javax.swing.JButton();
        qtdEstoque = new javax.swing.JTextField();
        BTSALVAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelatorio = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btsetv = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        soma = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        estoque = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        codProd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSaida = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        codEstoque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório");

        jPanel1.setBackground(new java.awt.Color(162, 230, 229));

        jLabel2.setText("Código venda:");

        TOTALvendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALvendasActionPerformed(evt);
            }
        });

        jLabel3.setText("Data:");

        jLabel4.setText("Valor total das venda:");

        jLabel5.setText("Qtd Em Estoque :");

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        bTapagar.setText("Excluir");
        bTapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTapagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código Relatório:");

        visualizar.setText("Exibir dados");
        visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarActionPerformed(evt);
            }
        });

        BTSALVAR.setText("Salvar");
        BTSALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSALVARActionPerformed(evt);
            }
        });

        tbRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodRelatorio", "CodTdsVenda", "Data", "Valor total ", "CodProd", "Entrada", "Saída", "Qtd_Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbRelatorio);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Relatório Das Vendas");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btsetv.setText("Pesquisa Venda");
        btsetv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsetvActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        soma.setText("Somar Todas Vendas");
        soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Valor Total De Todas Vendas:");

        estoque.setText("Pesquisa Estoque");
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });

        jLabel8.setText("Código Produto:");

        jLabel10.setText("Entrada:");

        jLabel11.setText("Saída:");

        txtSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaidaActionPerformed(evt);
            }
        });

        jLabel12.setText("Código do Estoque:");

        codEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jScrollPane1)
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(BTSALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bTapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodRe, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btsetv, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodVend, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TOTALvendas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codProd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(77, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(estoque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(codEstoque, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(42, 42, 42)
                        .addComponent(qtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soma, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodRe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodVend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codProd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btsetv)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estoque))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(soma))
                            .addComponent(qtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TOTALvendas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTSALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bTapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTapagarActionPerformed
          
        apagar();
        Connection conn=Conexao_BD.getConnection();
         
        int codVd=Integer.parseInt(txtCodVend.getText());
         
        try {

          
            String sql = "delete from venda where codVend=?";

            PreparedStatement patm = conn.prepareStatement(sql);

            patm.setInt(1, Integer.parseInt(txtCodVend.getText()));

            int res = patm.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Venda Execluida com Sucesso !", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Venda não Excluida !", "Error", JOptionPane.ERROR_MESSAGE);
            }

            patm.close();
            conn.close();

        } catch (Exception e) {
        }

    }//GEN-LAST:event_bTapagarActionPerformed

    private void TOTALvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALvendasActionPerformed
   
    }//GEN-LAST:event_TOTALvendasActionPerformed

    private void visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarActionPerformed
        
      //Método para visualizar relatorio;
      visualizaRelatorio();
        //evitarDuplicacao();
    }//GEN-LAST:event_visualizarActionPerformed
             //Método para visualizar todo Relatório;
    public void visualizaRelatorio(){
        
        DefaultTableModel modelo = (DefaultTableModel) tbRelatorio.getModel();
        modelo.setNumRows(0);
        //Instânciando objeto RelatorioDao;
        RelatorioDao dao = new RelatorioDao();
        
        for (RelatorioModel relat : dao.visualizarRelatorio()) {
            modelo.addRow(new Object []{
            
            relat.getCodRelatorio(),
            relat.getCodVendas(),
            relat.getData(),
            relat.getValorTtlvendas(),
            relat.getCodProd(),
            relat.getEntrada(),
            relat.getSaida(),
            relat.getQtd_Estoque()
            
            
            });
            
            
        }
        
    }
    
    
    
    
    private void BTSALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSALVARActionPerformed
         
        //Método para salvar relatório;
           salvarRelatorio();
    }//GEN-LAST:event_BTSALVARActionPerformed
       
    //Método para salvar relatorio;
      public void salvarRelatorio(){
        
           //Instânciando RelatorioDao;
        RelatorioDao dao = new RelatorioDao();
          
         //Instânciando RelatorioModel;
        RelatorioModel relat = new RelatorioModel();
        
        relat.setCodRelatorio(txtCodRe.getText());
        relat.setCodVendas(txtCodVend.getText());
        relat.setData(txtData.getText());
        relat.setValorTtlvendas(Double.parseDouble(TOTALvendas.getText()));
        relat.setCodProd(codProd.getText());
        relat.setEntrada(Integer.parseInt(txtEntrada.getText()));
        relat.setSaida(Integer.parseInt(txtSaida.getText()));
        relat.setQtd_Estoque(Integer.parseInt(qtdEstoque.getText()));
        //Setando os valores do objeto Relatoriodao;
        dao.adicionarRelatorio(relat);
        
      }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      limpalinha();
        limpar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btsetvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsetvActionPerformed
    
        setaDados();
        
    }//GEN-LAST:event_btsetvActionPerformed

    private void somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaActionPerformed
     setaValores();
    }//GEN-LAST:event_somaActionPerformed

    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
      
        //Método para buscar os dados do estoque pelo código;
         setaDadosEstoque();
    }//GEN-LAST:event_estoqueActionPerformed
      
      //Método para seta os valores do estoque;
      public void setaDadosEstoque(){
          
          //Instânciando umaconnection com a classe Conexao_BD;
          Connection conn=Conexao_BD.getConnection();
          
          try {
              
              String sql="SELECT codProd,entrada,saida,qtd_Estoque,data FROM estoque WHERE codEstoq=?";
              
              PreparedStatement patm = conn.prepareStatement(sql);
              patm.setString(1,codEstoque.getText());
              
              ResultSet rst =patm.executeQuery();
              
              while(rst.next()){
                  
                  String codprod=rst.getString("codProd");
                  int entrada=rst.getInt("entrada");
                  int saida=rst.getInt("saida");
                  int Estoque=rst.getInt("qtd_Estoque");
                  String date=rst.getString("data");
                  
                  codProd.setText(codprod+"");
                  txtEntrada.setText(entrada+"");
                  txtSaida.setText(saida+"");
                  qtdEstoque.setText(Estoque+"");
                  txtData.setText(date+"");
                  
              }
          } catch (Exception e) {
              
              JOptionPane.showMessageDialog(null, "Error ao seta dados do Estoque !","Opa Error", JOptionPane.ERROR_MESSAGE );
              
          }
          
      }
    
    
    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
     setaDados();
    }//GEN-LAST:event_txtDataActionPerformed

    private void codEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codEstoqueActionPerformed
       
    }//GEN-LAST:event_codEstoqueActionPerformed

    private void txtSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaidaActionPerformed
      
    }//GEN-LAST:event_txtSaidaActionPerformed
      
    public void exibirDados(){
          try {
            Connection Conn = Conexao_BD.getConnection();

            String sql = "SELECT * FROM relatorio";

            PreparedStatement Patm = Conn.prepareStatement(sql);

            ResultSet Rst = Patm.executeQuery();

            DefaultTableModel md = (DefaultTableModel) tbRelatorio.getModel();

            while (Rst.next()) {

                String[] lista = new String[]{Rst.getString("codRel"), Rst.getString("codVend"), Rst.getString("data"),
                     Rst.getString("valorTtvd"), Rst.getString("qtdPdisp")};

                md.addRow(lista);

            }

            Rst.close();
            Patm.close();
            Conn.close();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, " ");
        }
    }
     
    
    public void limpar(){
        txtCodRe.setText("");
        txtCodVend.setText("");
        txtData.setText("");
        qtdEstoque.setText("");
        TOTALvendas.setText("");
        total.setText("");
    }
   
    
    public void apagar(){
          Connection conn=Conexao_BD.getConnection();
         
        int codVd=Integer.parseInt(txtCodRe.getText());
         
        try {

          
            String sql = "delete from relatorio where codRel=?";

            PreparedStatement patm = conn.prepareStatement(sql);

            patm.setInt(1, Integer.parseInt(txtCodRe.getText()));

            int res = patm.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Relatório Execluido com Sucesso !", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Relatório não Excluido !", "Error", JOptionPane.ERROR_MESSAGE);
            }

            patm.close();
            conn.close();

        } catch (Exception e) {
        }
    }
     
    
     public  void setaDados(){
         
           try {
            Connection Conn = Conexao_BD.getConnection();
            
       
            
            String sql = "SELECT round(sum(ValorTotal),2) FROM vendar where dhata='"+txtData.getText()+"'";

            PreparedStatement Patm = Conn.prepareStatement(sql);
            
            ResultSet Rst = Patm.executeQuery();
            
             
        

            
            while (Rst.next()) {
                 String valorTotal= Rst.getString("round(sum(ValorTotal),2)");
                TOTALvendas.setText(""+Double.parseDouble(valorTotal)); 
                
               
            
             
            }

            Rst.close();
            Patm.close();
            Conn.close();

        } catch (SQLException e) {
        
         
            
            JOptionPane.showMessageDialog(null, "Valor não Encontrado !");
        }
        
     }
    
     
       public  void setaValores(){
         
           try {
            Connection Conn = Conexao_BD.getConnection();
        
            
            String sql = "SELECT round(sum(valorTtvd),2) FROM relatorio";

            PreparedStatement Patm = Conn.prepareStatement(sql);
            
            ResultSet Rst = Patm.executeQuery();
            
             
       

            
            while (Rst.next()) {
                 double TOTAL= Rst.getDouble("round(sum(valorTtvd),2)");
             total.setText(""
                     +TOTAL); 
               
            
             
            }

            Rst.close();
            Patm.close();
            Conn.close();

        } catch (SQLException e) {
        
         
            
            JOptionPane.showMessageDialog(null, "Valor não Encontrado !");
        }
        
     }
       
        public  void contaProduto(){
         
           try {
            Connection Conn = Conexao_BD.getConnection();
        
            
            String sql = "SELECT count(codProd)FROM produto";

            PreparedStatement Patm = Conn.prepareStatement(sql);
            
            ResultSet Rst = Patm.executeQuery();
            
             
       

            
            while (Rst.next()) {
                 int TOTAL= Rst.getInt("count(codProd)");
             qtdEstoque.setText(""
                     +TOTAL); 
               
            
             
            }

            Rst.close();
            Patm.close();
            Conn.close();

        } catch (SQLException e) {
        
         
            
            JOptionPane.showMessageDialog(null, "Produto não Contado !");
        }
        
     }
        
        public void evitarDuplicacao(){
          try {
            Connection Conn = Conexao_BD.getConnection();

            String sql = "SELECT DISTINCT codRel,codVend,data,valorTtvd,qtdPdisp FROM relatorio";

            PreparedStatement Patm = Conn.prepareStatement(sql);

            ResultSet Rst = Patm.executeQuery();

            DefaultTableModel md = (DefaultTableModel) tbRelatorio.getModel();

            while (Rst.next()) {

                String[] lista = new String[]{Rst.getString("codRel"), Rst.getString("codVend"), Rst.getString("data"),
                     Rst.getString("valorTtvd"), Rst.getString("qtdPdisp")};

                md.addRow(lista);

            }

            Rst.close();
            Patm.close();
            Conn.close();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, " ");
        }
    }
     
         public void limpalinha(){
        DefaultTableModel dm = (DefaultTableModel) tbRelatorio.getModel();
while(dm.getRowCount() > 0)
{
    dm.removeRow(0);
}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio_vd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio_vd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio_vd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio_vd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio_vd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTSALVAR;
    private javax.swing.JTextField TOTALvendas;
    private javax.swing.JButton bTapagar;
    private javax.swing.JButton btsetv;
    private javax.swing.JTextField codEstoque;
    private javax.swing.JTextField codProd;
    private javax.swing.JButton estoque;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField qtdEstoque;
    private javax.swing.JButton soma;
    private javax.swing.JTable tbRelatorio;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txtCodRe;
    private javax.swing.JTextField txtCodVend;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtSaida;
    private javax.swing.JButton visualizar;
    // End of variables declaration//GEN-END:variables
}
